repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: detect-private-key
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.2.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8
          - eslint-config-next@14.0.3
          - eslint-config-prettier@9.1.0
          - prettier@3.2.5
        files: frontend/.*\.(js|jsx|ts|tsx)$
        args: [--fix]
